// Drizzle schema. This is the contract every route file codes against; the table and
// column names follow docs/PLAN.md section "Phase 3, Data model".
//
// Reactions are append-only with a removed_at timestamp: rankings count rows where
// removed_at is null, and the yearly recap can replay history.

import {
  bigint,
  index,
  integer,
  pgTable,
  serial,
  text,
  timestamp,
  uniqueIndex,
} from 'drizzle-orm/pg-core';

export const users = pgTable('users', {
  id: serial('id').primaryKey(),
  discordId: text('discord_id').notNull().unique(),
  username: text('username').notNull(),
  avatar: text('avatar'),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
});

export const devices = pgTable(
  'devices',
  {
    id: serial('id').primaryKey(),
    userId: integer('user_id')
      .notNull()
      .references(() => users.id, { onDelete: 'cascade' }),
    name: text('name').notNull(),
    // SHA-256 of the device token. The token itself is only ever shown once.
    tokenHash: text('token_hash').notNull().unique(),
    lastSeen: timestamp('last_seen', { withTimezone: true }),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [index('devices_user_idx').on(t.userId)],
);

// Pending device logins. Row lives from POST /auth/device until the desktop polls the
// token out or the code expires. Never referenced by other tables.
export const deviceLogins = pgTable('device_logins', {
  id: serial('id').primaryKey(),
  code: text('code').notNull().unique(),
  deviceName: text('device_name').notNull(),
  // Set by the OAuth callback; null until the user finished logging in.
  deviceId: integer('device_id').references(() => devices.id, { onDelete: 'cascade' }),
  // The plaintext token, kept only until the desktop collects it, then nulled.
  token: text('token'),
  expiresAt: timestamp('expires_at', { withTimezone: true }).notNull(),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
});

export const clips = pgTable(
  'clips',
  {
    // Random URL-safe id (12 chars), generated by the backend, used in player URLs.
    id: text('id').primaryKey(),
    userId: integer('user_id')
      .notNull()
      .references(() => users.id, { onDelete: 'cascade' }),
    game: text('game'),
    title: text('title'),
    durationMs: integer('duration_ms').notNull(),
    width: integer('width'),
    height: integer('height'),
    sizeAv1: bigint('size_av1', { mode: 'number' }),
    sizeH264: bigint('size_h264', { mode: 'number' }),
    keyAv1: text('key_av1').notNull(),
    keyH264: text('key_h264').notNull(),
    keyThumb: text('key_thumb').notNull(),
    recordedAt: timestamp('recorded_at', { withTimezone: true }).notNull(),
    uploadedAt: timestamp('uploaded_at', { withTimezone: true }),
    // pending -> ready (after /complete) -> deleted
    status: text('status').notNull().default('pending'),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    index('clips_user_idx').on(t.userId),
    index('clips_recorded_idx').on(t.recordedAt),
    index('clips_status_idx').on(t.status),
  ],
);

export const posts = pgTable(
  'posts',
  {
    id: serial('id').primaryKey(),
    clipId: text('clip_id')
      .notNull()
      .references(() => clips.id, { onDelete: 'cascade' }),
    guildId: text('guild_id').notNull(),
    channelId: text('channel_id').notNull(),
    messageId: text('message_id').notNull(),
    postedAt: timestamp('posted_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    uniqueIndex('posts_message_idx').on(t.messageId),
    index('posts_clip_idx').on(t.clipId),
  ],
);

export const reactions = pgTable(
  'reactions',
  {
    id: serial('id').primaryKey(),
    postId: integer('post_id')
      .notNull()
      .references(() => posts.id, { onDelete: 'cascade' }),
    userDiscordId: text('user_discord_id').notNull(),
    emoji: text('emoji').notNull(),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
    removedAt: timestamp('removed_at', { withTimezone: true }),
  },
  (t) => [index('reactions_post_idx').on(t.postId, t.userDiscordId, t.emoji)],
);

export const events = pgTable(
  'events',
  {
    id: serial('id').primaryKey(),
    guildId: text('guild_id').notNull(),
    year: integer('year').notNull(),
    // open -> rendering -> posted
    status: text('status').notNull().default('open'),
    // Frozen ranking as JSON text, set when the event opens.
    ranking: text('ranking'),
    compilationKey: text('compilation_key'),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [uniqueIndex('events_guild_year_idx').on(t.guildId, t.year)],
);
