// Drizzle schema. This is the contract every route file codes against; the table and
// column names follow docs/PLAN.md section "Phase 3, Data model".
//
// Reactions are append-only with a removed_at timestamp: rankings count rows where
// removed_at is null, and the yearly recap can replay history.

import {
  bigint,
  boolean,
  index,
  integer,
  pgTable,
  serial,
  text,
  timestamp,
  uniqueIndex,
} from 'drizzle-orm/pg-core';

export const users = pgTable('users', {
  id: serial('id').primaryKey(),
  discordId: text('discord_id').notNull().unique(),
  username: text('username').notNull(),
  avatar: text('avatar'),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
});

export const devices = pgTable(
  'devices',
  {
    id: serial('id').primaryKey(),
    userId: integer('user_id')
      .notNull()
      .references(() => users.id, { onDelete: 'cascade' }),
    name: text('name').notNull(),
    // SHA-256 of the device token. The token itself is only ever shown once.
    tokenHash: text('token_hash').notNull().unique(),
    lastSeen: timestamp('last_seen', { withTimezone: true }),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [index('devices_user_idx').on(t.userId)],
);

// A browser session from the "Login with Discord" web flow, the same shape as `devices`: a
// random token shown once, only its hash kept, so it can be revoked (logout) by deleting the
// row - which a sealed cookie or a bare JWT could not do.
export const browserSessions = pgTable(
  'browser_sessions',
  {
    id: serial('id').primaryKey(),
    userId: integer('user_id')
      .notNull()
      .references(() => users.id, { onDelete: 'cascade' }),
    tokenHash: text('token_hash').notNull().unique(),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
    lastSeen: timestamp('last_seen', { withTimezone: true }),
    expiresAt: timestamp('expires_at', { withTimezone: true }).notNull(),
  },
  (t) => [index('browser_sessions_user_idx').on(t.userId)],
);

// Pending device logins. Row lives from POST /auth/device until the desktop polls the
// token out or the code expires. Never referenced by other tables.
export const deviceLogins = pgTable('device_logins', {
  id: serial('id').primaryKey(),
  code: text('code').notNull().unique(),
  deviceName: text('device_name').notNull(),
  // Set by the OAuth callback; null until the user finished logging in.
  deviceId: integer('device_id').references(() => devices.id, { onDelete: 'cascade' }),
  // The plaintext token, kept only until the desktop collects it, then nulled.
  token: text('token'),
  // SHA-256 of the poll secret handed to the desktop once, in the POST /auth/device response.
  // Only a caller holding that secret may poll this code, so the human-readable code is not the
  // only thing between a stranger and the device token. The '' default is there so the migration
  // cannot fail on a live row; hashToken() always returns 64 hex chars, never '', so a row left
  // with the default can never be polled.
  pollSecretHash: text('poll_secret_hash').notNull().default(''),
  expiresAt: timestamp('expires_at', { withTimezone: true }).notNull(),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
});

export const clips = pgTable(
  'clips',
  {
    // Random URL-safe id (12 chars), generated by the backend, used in player URLs.
    id: text('id').primaryKey(),
    userId: integer('user_id')
      .notNull()
      .references(() => users.id, { onDelete: 'cascade' }),
    game: text('game'),
    title: text('title'),
    durationMs: integer('duration_ms').notNull(),
    width: integer('width'),
    height: integer('height'),
    sizeAv1: bigint('size_av1', { mode: 'number' }),
    sizeH264: bigint('size_h264', { mode: 'number' }),
    keyAv1: text('key_av1').notNull(),
    keyH264: text('key_h264').notNull(),
    keyThumb: text('key_thumb').notNull(),
    recordedAt: timestamp('recorded_at', { withTimezone: true }).notNull(),
    uploadedAt: timestamp('uploaded_at', { withTimezone: true }),
    // pending -> ready (after /complete) -> deleted
    status: text('status').notNull().default('pending'),
    // Discord user ids who were in the owner's voice channel when the clip was captured, as a
    // JSON array string - the same convention as guild_settings.seed_emojis, so the column stays
    // plain text and only the route layer ever sees the parsed array. The bot @mentions these
    // people on the post. Never part of the public clip JSON: who you were playing with is not
    // something the player page or the listing should hand out.
    participants: text('participants').notNull().default('[]'),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    index('clips_user_idx').on(t.userId),
    index('clips_recorded_idx').on(t.recordedAt),
    index('clips_status_idx').on(t.status),
  ],
);

export const posts = pgTable(
  'posts',
  {
    id: serial('id').primaryKey(),
    clipId: text('clip_id')
      .notNull()
      .references(() => clips.id, { onDelete: 'cascade' }),
    guildId: text('guild_id').notNull(),
    channelId: text('channel_id').notNull(),
    messageId: text('message_id').notNull(),
    postedAt: timestamp('posted_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    uniqueIndex('posts_message_idx').on(t.messageId),
    index('posts_clip_idx').on(t.clipId),
  ],
);

export const reactions = pgTable(
  'reactions',
  {
    id: serial('id').primaryKey(),
    postId: integer('post_id')
      .notNull()
      .references(() => posts.id, { onDelete: 'cascade' }),
    userDiscordId: text('user_discord_id').notNull(),
    emoji: text('emoji').notNull(),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
    removedAt: timestamp('removed_at', { withTimezone: true }),
  },
  (t) => [index('reactions_post_idx').on(t.postId, t.userDiscordId, t.emoji)],
);

export const events = pgTable(
  'events',
  {
    id: serial('id').primaryKey(),
    guildId: text('guild_id').notNull(),
    year: integer('year').notNull(),
    // open -> rendering -> posted
    status: text('status').notNull().default('open'),
    // Frozen ranking as JSON text, set when the event opens.
    ranking: text('ranking'),
    compilationKey: text('compilation_key'),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [uniqueIndex('events_guild_year_idx').on(t.guildId, t.year)],
);

// Per-guild configuration written by `/clips setup` in the bot: where clips get posted and
// which emojis the bot seeds on each post. `seed_emojis` is a JSON array string so the
// column stays plain text (the routes parse it before it reaches the wire). `locale` is the
// language the bot replies in for that guild; defaults to Spanish, the community's language.
//
// `name`, `icon` and `slug` back the public per-guild clip site (docs/PLAN.md phase 5) and
// are nullable because every guild configured before that feature has none of them yet.
// `icon` is a bare Discord CDN hash, the same convention as `users.avatar`, never a URL.
// `slug` is the human-readable URL segment (e.g. "famafia"); set once by a human running
// `/clips setup` again, never derived automatically from `name`.
export const guildSettings = pgTable(
  'guild_settings',
  {
    guildId: text('guild_id').primaryKey(),
    channelId: text('channel_id').notNull(),
    seedEmojis: text('seed_emojis').notNull().default('["🔥","😂","💀"]'),
    locale: text('locale').notNull().default('es'),
    // Whether the bot @mentions the people who were in voice with the clip owner at capture
    // time. On by default: the whole point of the tag is that the people in the play get to see
    // it, and a guild that finds it noisy turns it off with `/clips config`.
    tagVoiceMembers: boolean('tag_voice_members').notNull().default(true),
    name: text('name'),
    icon: text('icon'),
    slug: text('slug'),
    updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [uniqueIndex('guild_settings_slug_idx').on(t.slug)],
);
