// The "manage this clip" button that rides along on every clip post, and the ephemeral menu
// behind it.
//
// Two very different actions hide behind one button, and the difference is the whole reason
// the menu exists:
//
//   - Hide deletes the *Discord message* and nothing else. The clip stays in the bucket, on
//     the site and in the rankings. It is the "wrong channel / not now" button.
//   - Delete calls DELETE /internal/clips/:id and the clip is gone everywhere: files, row,
//     votes, every post of it. It asks for a confirmation first, because nothing undoes it.
//
// Authorization is re-read from the backend on *every* click, never carried over from the
// click before it: an ephemeral message lives for as long as the person keeps its tab open,
// so a "you may manage this" decided at menu time would be a decision made minutes ago about
// a clip that may since have changed hands or been deleted.
//
// The button on the public post carries a fixed label. Component labels are baked into the
// message and Discord does not localize them per viewer, so a Spanish server and an English
// server reading the same post would see the same word whatever we did; the ephemeral replies
// *are* built at click time and go through t() like everything else.

import {
  ActionRowBuilder,
  ButtonBuilder,
  ButtonStyle,
  MessageFlags,
  PermissionFlagsBits,
} from 'discord.js';

import { localeForGuild, t } from './i18n.js';

/** customId prefix every component in this module shares. */
const PREFIX = 'clip';

/** The actions a customId may name, and how many ids each one carries after the clip id. */
const ACTIONS = {
  menu: 0,
  hide: 2,
  delcfm: 2,
  delgo: 2,
  delcancel: 2,
};

/** Backend clip ids are 12 url-safe characters; this is deliberately a little looser. */
const CLIP_ID = /^[A-Za-z0-9_-]{1,32}$/;
/** Discord snowflakes are decimal and 17-20 digits long today. */
const SNOWFLAKE = /^\d{1,25}$/;

/** Never let a clip title or a username in an ephemeral panel ping anyone. */
const NO_MENTIONS = { parse: [] };

/**
 * The row that goes on the public post.
 *
 * Secondary, because it is chrome: the clip is the message, and this is the small grey button
 * next to it. The label is locale-neutral by necessity (see the header) - the gear carries
 * most of the meaning, and everything the button leads to is translated.
 *
 * @param {string} clipId
 * @returns {ActionRowBuilder<ButtonBuilder>}
 */
export function manageRow(clipId) {
  return new ActionRowBuilder().addComponents(
    new ButtonBuilder()
      .setCustomId(`${PREFIX}:menu:${clipId}`)
      .setStyle(ButtonStyle.Secondary)
      .setEmoji('⚙️')
      .setLabel('Manage'),
  );
}

/**
 * Splits a customId into its parts, or returns null when it is not one of ours or is not
 * shaped the way we write them.
 *
 * Nothing here is user-typed - every id is generated by the backend or by Discord - so this
 * is not escaping, it is a guard against acting on a customId from an older or a broken
 * build. A customId we do not recognise is left alone rather than answered.
 *
 * @param {unknown} customId
 * @returns {{ action: keyof typeof ACTIONS, clipId: string, channelId?: string, messageId?: string } | null}
 */
function parseCustomId(customId) {
  if (typeof customId !== 'string') return null;
  const [prefix, action, clipId, channelId, messageId, ...rest] = customId.split(':');
  if (prefix !== PREFIX || rest.length > 0) return null;
  if (!Object.hasOwn(ACTIONS, action)) return null;
  if (!CLIP_ID.test(clipId ?? '')) return null;
  if (ACTIONS[action] === 0) {
    if (channelId !== undefined || messageId !== undefined) return null;
    return { action: /** @type {keyof typeof ACTIONS} */ (action), clipId };
  }
  if (!SNOWFLAKE.test(channelId ?? '') || !SNOWFLAKE.test(messageId ?? '')) return null;
  return { action: /** @type {keyof typeof ACTIONS} */ (action), clipId, channelId, messageId };
}

/**
 * Wraps backend text in a code span so a clip title cannot turn the rest of the sentence into
 * markdown. Same helper, same reasoning as commands.js's quoted().
 * @param {unknown} value
 */
function quoted(value) {
  return `\`${String(value).replace(/`/g, '')}\``;
}

/**
 * Logger that tolerates a partial `log` object, like commands.js. Duplicated rather than
 * shared: it is four lines, and a "utils" module for it would be worse.
 * @param {{ error?: Function, warn?: Function, info?: Function } | undefined} log
 */
function normalizeLog(log) {
  const target = log ?? console;
  /** @param {'error' | 'warn' | 'info'} name */
  const pick = (name) =>
    typeof target[name] === 'function' ? target[name].bind(target) : console.error.bind(console);
  return { error: pick('error'), warn: pick('warn'), info: pick('info') };
}

/** @param {any} err */
function errorText(err) {
  return err?.stack ?? err?.message ?? String(err);
}

/** @param {any} err */
function statusOf(err) {
  return Number(err?.status ?? 0);
}

/**
 * The two-button panel: hide here, or delete everywhere.
 * @param {import('@cos-nostra/shared').Locale} locale
 * @param {{ clipId: string, channelId: string, messageId: string }} target
 */
function menuRow(locale, { clipId, channelId, messageId }) {
  const suffix = `${clipId}:${channelId}:${messageId}`;
  return new ActionRowBuilder().addComponents(
    new ButtonBuilder()
      .setCustomId(`${PREFIX}:hide:${suffix}`)
      .setStyle(ButtonStyle.Secondary)
      .setLabel(t(locale, 'manage.hideButton')),
    new ButtonBuilder()
      .setCustomId(`${PREFIX}:delcfm:${suffix}`)
      .setStyle(ButtonStyle.Danger)
      .setLabel(t(locale, 'manage.deleteButton')),
  );
}

/**
 * The confirmation panel. Danger on the confirm, so the destructive one is the one that looks
 * destructive.
 * @param {import('@cos-nostra/shared').Locale} locale
 * @param {{ clipId: string, channelId: string, messageId: string }} target
 */
function confirmRow(locale, { clipId, channelId, messageId }) {
  const suffix = `${clipId}:${channelId}:${messageId}`;
  return new ActionRowBuilder().addComponents(
    new ButtonBuilder()
      .setCustomId(`${PREFIX}:delgo:${suffix}`)
      .setStyle(ButtonStyle.Danger)
      .setLabel(t(locale, 'manage.confirmButton')),
    new ButtonBuilder()
      .setCustomId(`${PREFIX}:delcancel:${suffix}`)
      .setStyle(ButtonStyle.Secondary)
      .setLabel(t(locale, 'manage.cancelButton')),
  );
}

/**
 * Deletes a message we posted, tolerating the case where it is already gone.
 * @param {any} client
 * @param {string} channelId
 * @param {string} messageId
 * @param {{ warn: Function }} log
 */
async function deleteMessage(client, channelId, messageId, log) {
  try {
    const channel = await client.channels.fetch(channelId);
    await channel.messages.delete(messageId);
  } catch (err) {
    // Someone deleted it by hand, the bot lost Manage Messages, the channel is gone. None of
    // those are worth telling the user about: the message is not there, which is what they
    // asked for.
    log.warn(`could not delete message ${messageId} in ${channelId}: ${errorText(err)}`);
  }
}

/**
 * Attaches the clip button handler to a discord.js client.
 * @param {{ client: any, backend: any, log?: { error?: Function, warn?: Function, info?: Function } }} deps
 * @returns {void}
 */
export function registerManage({ client, backend, log }) {
  if (!client) throw new TypeError('registerManage: client is required');
  if (!backend) throw new TypeError('registerManage: backend is required');
  const logger = normalizeLog(log);

  /**
   * Everything a click does once it has been acknowledged and the clip has been read.
   * @param {any} interaction
   * @param {{ action: string, clipId: string, channelId?: string, messageId?: string }} parsed
   * @param {import('@cos-nostra/shared').Locale} locale
   * @param {(payload: any) => Promise<unknown>} finish
   */
  async function act(interaction, parsed, locale, finish) {
    const { action, clipId } = parsed;

    // Re-read on every click. getClip answers null for a 404, which here means the clip is
    // already gone - deleted by the other half of a double click, or by someone else.
    const clip = await backend.getClip(clipId);
    if (!clip) return finish({ content: t(locale, 'manage.gone') });

    const isOwner = interaction.user?.id === clip.owner?.discordId;
    const isModerator = Boolean(
      interaction.memberPermissions?.has(PermissionFlagsBits.ManageGuild),
    );
    if (!isOwner && !isModerator) {
      logger.info(`clip ${clipId}: ${interaction.user?.id} may not manage it`);
      return finish({ content: t(locale, 'manage.notYours') });
    }

    const label = quoted(clip.title || clip.game || t(locale, 'common.untitledClip'));

    if (action === 'menu') {
      // The message the button lives on is the one hide and delete will remove, so the
      // target travels in the customId rather than being looked up again later.
      const target = {
        clipId,
        channelId: String(interaction.message?.channelId ?? ''),
        messageId: String(interaction.message?.id ?? ''),
      };
      if (!SNOWFLAKE.test(target.channelId) || !SNOWFLAKE.test(target.messageId)) {
        logger.warn(`clip ${clipId}: menu clicked on a message with no usable ids`);
        return finish({ content: t(locale, 'manage.gone') });
      }
      return finish({
        content: t(locale, 'manage.menu', { clip: label }),
        components: [menuRow(locale, target)],
      });
    }

    const target = {
      clipId,
      channelId: /** @type {string} */ (parsed.channelId),
      messageId: /** @type {string} */ (parsed.messageId),
    };

    if (action === 'hide') {
      await deleteMessage(client, target.channelId, target.messageId, logger);
      logger.info(`clip ${clipId}: post ${target.messageId} hidden by ${interaction.user?.id}`);
      return finish({ content: t(locale, 'manage.hidden') });
    }

    if (action === 'delcfm') {
      return finish({
        content: t(locale, 'manage.confirmPrompt', { clip: label }),
        components: [confirmRow(locale, target)],
      });
    }

    if (action === 'delcancel') {
      return finish({
        content: t(locale, 'manage.menu', { clip: label }),
        components: [menuRow(locale, target)],
      });
    }

    // delgo: the irreversible one.
    try {
      await backend.deleteClip(clipId);
    } catch (err) {
      if (statusOf(err) !== 404) throw err;
      // A 404 means someone got there first, which is the outcome that was asked for.
      logger.info(`clip ${clipId}: already deleted before this click`);
    }
    await deleteMessage(client, target.channelId, target.messageId, logger);
    logger.info(`clip ${clipId}: deleted everywhere by ${interaction.user?.id}`);
    return finish({ content: t(locale, 'manage.deleted') });
  }

  /** @param {any} interaction */
  async function handle(interaction) {
    if (!interaction?.isButton?.()) return;
    const parsed = parseCustomId(interaction.customId);
    if (!parsed) {
      // Either not ours, or a customId a different build wrote. Answering would steal the
      // interaction from whoever it does belong to, so it is left alone.
      if (String(interaction.customId ?? '').startsWith(`${PREFIX}:`)) {
        logger.warn(`ignoring an unrecognised clip customId: ${interaction.customId}`);
      }
      return;
    }

    // delcfm and delcancel transform the ephemeral panel in place; menu, hide and delgo open
    // a new ephemeral reply, because menu is clicked on the *public* post (which must not be
    // edited) and the other two do work worth deferring for. Each click is its own
    // interaction either way: update() edits the message, not a previous interaction.
    const inPlace = parsed.action === 'delcfm' || parsed.action === 'delcancel';
    /** @type {(payload: any) => Promise<unknown>} */
    let finish;
    if (inPlace) {
      finish = (payload) =>
        interaction.update({ components: [], ...payload, allowedMentions: NO_MENTIONS });
    } else {
      try {
        await interaction.deferReply({ flags: MessageFlags.Ephemeral });
      } catch (err) {
        // Nothing was acknowledged, so there is nowhere to report this.
        logger.error(`clip ${parsed.action}: could not defer: ${errorText(err)}`);
        return;
      }
      finish = (payload) =>
        interaction.editReply({ components: [], ...payload, allowedMentions: NO_MENTIONS });
    }

    // After the acknowledgement: the three-second window belongs to that, not to a language
    // lookup. localeForGuild never throws.
    const locale = await localeForGuild(backend, interaction.guildId);

    try {
      await act(interaction, parsed, locale, finish);
    } catch (err) {
      const status = statusOf(err);
      logger.error(
        `clip ${parsed.action} on ${parsed.clipId} failed${status ? ` (status ${status})` : ''}: ${errorText(err)}`,
      );
      try {
        await finish({ content: t(locale, 'manage.failed'), components: [] });
      } catch (replyErr) {
        logger.warn(`could not report a clip button failure: ${errorText(replyErr)}`);
      }
    }
  }

  client.on('interactionCreate', (interaction) => {
    // discord.js does not await this listener, so nothing may escape as a rejection.
    handle(interaction).catch((err) => logger.error(`clip button failed: ${errorText(err)}`));
  });
}
